// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhkdsmfekcgauurhvbdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoa2RzbWZla2NnYXV1cmh2YmRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NDU0NTYsImV4cCI6MjA3MTAyMTQ1Nn0.wg8RX7wZGJaEKyy7I15EQtNh8kcH9MX8St7WXGvdUhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});